server:
  port: 0

spring:
  application:
    name: AUTH-SERVICE

  data:
    mongodb:
      uri: mongodb://185.125.202.202:27017/luna_users
      database: luna_users

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: common, eclient, secrets, kafka

springdoc:
  swagger-ui:
    path: /auth/swagger/swagger-ui.html
  api-docs:
    path: /auth/swagger/swagger-ad
