server:
  port: 0

spring:
  application:
    name: USERS-SERVICE

  data:
    mongodb:
      uri: mongodb://185.125.202.202:27017/luna_users
      database: luna_users

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: eclient, kafka, secrets

springdoc:
  swagger-ui:
    path: /users/swagger/swagger-ui.html
  api-docs:
    path: /users/swagger/swagger-ad