server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: eclient, gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://94.181.164.137:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
