server:
  port: 0

spring:
  application:
    name: GROUPS-SERVICE

  data:
    mongodb:
      uri: mongodb://185.125.202.202:27017/luna_groups
      database: luna_groups

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: common, eclient, secrets