server:
  port: 0

spring:
  application:
    name: TASKS-SERVICE

  data:
    mongodb:
      uri: mongodb://185.125.202.202:27017/luna_tasks
      database: luna_tasks

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: eclient, secrets